### ISSUE TITLE
bugs after install and config it

### ISSUE THREAD

**Issue by beatwade** [angyvolin/silex-workflow#1]
Identifier "twig" does not contain an object definition.

![image](https://user-images.githubusercontent.com/6858148/27364145-4a9a5764-566b-11e7-89f7-0760c8303a7a.png)

**Comment by angyvolin** [comment]
Hi. Thank you for your report.

Starting from version 2, Pimple is more strict about services: once accessed, any service can't be extended no more. Pimple 'frozes' such a service and prevents it from any further modifications (the case on your screenshot). That's why Silex documentation describes one more convention: You need to watch out in what order you do certain things when interacting with providers.

It seems like 'twig' service is accessed before WorkflowServiceProvider is able to extend it. At that moment the service is already frozen thus can't be modified in any way. 

You can either try to debug your application, locate those places where 'twig' service is accessed not in time and fix them, or register WorkflowServiceProvider right after TwigServiceProvider registration but before any 'twig' service usage.

**Comment by beatwade** [comment]
Hi, Thanks your description. since pimple is so strict , and I have check my priority of my container , twig is before workflow service . 
so I have to change every bootable service to register to fix it , do you think it's the best practice?
what the different between register and boot in this workflow service? I'll create a pull request
thanks again

**Comment by angyvolin** [comment]
Hi, @beatwade. Thank you for your time.
I wrote several comments in your pull request. Can you manage to resolve those issues so I can accept your PR?

The main reason to use **application boot** for registering workflow configuration, is to allow another service providers adding their own workflow configs if any.
